include::../shared-doc/attributes.adoc[]

= ejb-remote: EJB Over HTTP with JWT Authentication Example
:author: Lin Gao
:level: Intermediate
:technologies: EJB, HTTP, JWT

[abstract]
The `ejb-remote` quickstart uses EJB and JNDI to demonstrate how to access an EJB, deployed to {productName}, from a remote Java client application.

:standalone-server-type: default
:archiveType: jar
// Override the archive name
:archiveDir: {artifactId}/server-side/target
:archiveName: {artifactId}-server-side

== What is it?

The `ejb-over-http-jwt` quickstart shows how to access an EJB from a remote Java client application via HTTP transport.
It demonstrates the use of EJB over HTTP and JWT/BEARER authentication in {productNameFull}.

There are two components to this example:

. A server side component:
+
The server component includes one stateless EJB to calculate 2 numbers.

. A remote client application that accesses the server component.
+
The remote client application calls EJB by getting JWT token first via HTTP transport.

Each component is defined in its own standalone Maven module. The quickstart provides a top level Maven module to simplify the packaging of the artifacts.

== Build and Run the Client Application

. Navigate to the client subdirectory.
+
[source,options="nowrap"]
----
$ cd ../client
----

. Compile the client code.
+
[source,options="nowrap"]
----
$ mvn clean compile
----

. Execute the client application within Maven.
+
[source,options="nowrap"]
----
$ mvn exec:exec
----

[NOTE]
====
If you consider running the client execution manually then you can execute

[source,sh,options="nowrap"]
----
mvn clean compile assembly:single
----

and run the client application with

[source,sh,options="nowrap"]
----
java -jar target/ejb-remote-client-jar-with-dependencies.jar
----
====
